apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-message
  labels:
    app: backend-message
spec:
  selector:
    matchLabels:
      app: backend-message
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-message
    spec:
      containers:
      - name: container-message
        image: crist/jenkins-docker-hub:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-messages
spec:
  selector:
    app: backend-message
  type: NodePort
  ports:
  - name: port-message
    protocol: TCP
    port: 8080
    targetPort: 8080
